name: Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  create-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v6
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-world:latest
    - name: Build the Docker image
    - uses: MaximilianoBz/dockerhub-buildpush@v1.1
      with:
        registry_url: docker.io
        repository_name: automation_devops
        user_name: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Image Build Version
        image_version: latest
        # Docker File Directory, Default Current Directory (.)
        docker_file: .
        
        
