# This is a basic workflow to help you get started with Actions

name: greeting_jobs

# Controls when the workflow will run
on:
  workflow_dispatch:

env: 
  DAY: Monday
  Name: Andres

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   greeting_job:
    runs-on: ubuntu-latest
    env: 
      Greeting: Good Morning

    steps:
      - name: "Its Monday!"
        run: echo "$Greeting $Name!. Its $DAY!"

      # Runs a set of commands using the runners shell
      - name: "I like mondays"
        run: echo "$Greeting, $Name you like $DAY"
