# Labb 2 - Workflow Dispatch, If-statser och Needs i GitHub Actions 

name: labb_2 

on: 
  workflow_dispatch: 
    inputs: 
      message:
        description: "Write a message"
        required: true
        default: "Hi from workflow"
        
jobs: 
  show-input:
    runs-on: ubuntu-latest
    steps: 
      - name: "Show imput"
        run: echo "You wrote:${{ github.event.inputs.message }}"
