# Labb - Workflow Dispatch, If-satser och Needs

# 1a) Lägg till en workflow_dispatch-trigger som tar in minst en input (till exempel sträng)  

name: Andres - labb_2

on:
  workflow_dispatch:
     inputs:
       message:
          description: "My name is Andres"
          required: true
          default: "Hello from Workflow, Andres!"

# b) Lägg till ett jobb som kör ett skript som visar upp värdet från inputen. 
# 2b) Lägg till två steg: Ett som bara körs om variabel == ett bestämt värde, och ett som bara körs om variabel == något annat

jobs:
  show-input:
    runs-on: ubuntu-latest
    steps:
    -  name: Show imput
       run: echo "You wrote:${{ github.event.inputs.message }}"
       
    -  name: if its a variable == "hello"
       if: ${{ github.event.inputs.variable == "hello" }}
       run: echo "The variable is hello"
       
    -  name: if its not a variable != "hello" 
       if: ${{ github.event.inputs.variable != "hello" }}
       run: echo "The variable is something else than hello"
