# Labb 2 - Workflow Dispatch, If-statser och Needs i GitHub Actions 

name: labb_2 

on: 
  workflow_dispatch: 
    inputs: 
      variable:
        description: "Write a message"
        required: true
        default: "hello"
        
jobs: 
  check-input:
    runs-on: ubuntu-latest
    steps: 
      - name: "Check imput"
        run: echo "You wrote:${{ github.event.inputs.variable }}"

      - name: Runs if variable == 'hello'
        if: ${{ github.event.inputs.variable == 'hello' }}
        run: echo "You typed hello!"

      - name: Runs if variable != 'hello'
        if: ${{ github.event.inputs.variable != 'hello' }}
        run: echo "You typed something else!"
