# Labb 2 - Workflow Dispatch, If-statser och Needs i GitHub Actions 

name: labb_2 

on: 
  workflow_dispatch: 
    inputs: 
      variable:
        description: "Write a message"
        required: true
        default: "hello"
        
jobs: 
  check-input:
    runs-on: ubuntu-latest
    steps: 
      - name: "Check imput"
        run: echo "You wrote:${{ github.event.inputs.variable }}"

      - name: if its a variable == "hello"
        if: ${{ github.event.inputs.variable == "hello" }}
        run: echo "The variable is 'hello'"

      - name: if its not a variable
        if: ${{ github.event.inputs.variable != "hello" }}
        run: echo "The variable is something else than 'hello'"
