# Labb 2 - Workflow Dispatch, If-statser och Needs i GitHub Actions 

name: labb_2 

on: 
  workflow_dispatch: 
    inputs: 
      run_test:
        type: boolean
        description: "Write a message"
        required: true
        default: true
        
        
jobs:
  tests:
    runs-on: ubuntu-latest
    if: ${{  github.event.input.run_test == 'true' }}
    steps: 
      - name: "Running tests"
        run: echo "Running all tests"

      - name: Runs all the time
        if: ${{ always() }}
        run: echo "This test is running always"

  build: 
    runs-on: ubuntu-latest
    needs: tests
    steps: 
      - name: Building project
        run: echo "Project builds..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploying project
        run: echo "Deploying project"
