
# Labb - Workflow Dispatch, If-satser och Needs

name: Andres - labb_2

on:
  workflow_dispatch:
     inputs:
       variable:
          description: "My name is Andres"
          required: true
          default: "Hello from Workflow, Andres!"

jobs:
  check-input:
    runs-on: ubuntu-latest
    steps:
      -  name: Show imput
         run: echo "You wrote:${{ github.event.inputs.variable }}"
       
      -  name: if its a variable == 'hello'
         if: ${{ github.event.inputs.variable == 'hello' }}
         run: echo "The variable is hello"
       
      -  name: if its not a variable != 'hello' 
         if: ${{ github.event.inputs.variable != 'hello' }}
         run: echo "The variable is something else than hello'
